--liquibase formatted sql
--changeset samueljuniior:1.1

CREATE TABLE TB_ENDERECO (
     ID_ENDERECO SERIAL PRIMARY KEY,
     LONGRADOURO VARCHAR (255),
     COMPLEMENTO VARCHAR (255),
     BAIRRO VARCHAR (255),
     UF VARCHAR (2)
);

CREATE TABLE TB_USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    ID_ENDERECO BIGINT UNIQUE REFERENCES TB_ENDERECO(ID_ENDERECO)
);