server:
  port: 8080
  error:
    include-stacktrace: ON_PARAM

spring:
  application:
    name: @project.artifactId@

  datasource:
    continue-on-error: true
    url: jdbc:postgresql://localhost:5432/rest_api_user_crud
    platform: postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    root: info
    br: debug

integrations:
  viacep:
    base-url: viacep.com.br